const HTML_RESERVED_TAGS = [
    "a",
    "abbr",
    "address",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "bdi",
    "bdo",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "cite",
    "code",
    "col",
    "colgroup",
    "data",
    "datalist",
    "dd",
    "del",
    "details",
    "dfn",
    "dialog",
    "div",
    "dl",
    "dt",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hr",
    "html",
    "i",
    "iframe",
    "img",
    "input",
    "ins",
    "kbd",
    "label",
    "legend",
    "li",
    "link",
    "main",
    "map",
    "mark",
    "meta",
    "meter",
    "nav",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "param",
    "picture",
    "pre",
    "progress",
    "q",
    "rp",
    "rt",
    "ruby",
    "s",
    "samp",
    "script",
    "section",
    "select",
    "small",
    "source",
    "span",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "svg",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "u",
    "ul",
    "var",
    "video",
    "wbr",

    "acronym", // Not supported in HTML5. Use <abbr> instead.
    "applet", // Not supported in HTML5. Use <embed> or <object> instead.
    "basefont", // Not supported in HTML5. Use CSS instead.
    "big", // Not supported in HTML5. Use CSS instead.
    "center", // Not supported in HTML5. Use CSS instead.
    "dir", // Not supported in HTML5. Use <ul> instead.
    "font", // Not supported in HTML5. Use CSS instead.
    "frame", // Not supported in HTML5.
    "frameset", // Not supported in HTML5.
    "noframes", // Not supported in HTML5.
    "strike", // Not supported in HTML5. Use <del> or <s> instead.
    "tt", // Not supported in HTML5. Use CSS instead.
]


module.exports = { HTML_RESERVED_TAGS };